### ISSUE TITLE
Ampache 3.8.4

### ISSUE THREAD

**Issue by aruhier** [victor-rds/docker-ampache-fpm#1]
Hi,
Ampache 3.8.4 is out, could you trigger a new build please?

Also, as you do not have tag on your docker, could you automatically trigger a new build every x days (every week, for example) in dockerhub, to avoid this can of issue?

Thanks a lot!

**Comment by victor-rds** [comment]
I thought that linking to the ampache/ampache repo would trigger this, looks like they don't update as I expected.
I will fix a Linux dependency and trigger a new build

**Comment by aruhier** [comment]
Thanks a lot!

**Comment by victor-rds** [comment]
@Anthony25 Now is up, sorry for the delay, the php-fpm image update broke my build, an ampache composer dependency doesn't work with php 7.2, I fixed changed to php:7.1-fpm until ampache fix this.

**Comment by aruhier** [comment]
Ok, no worries!
