### ISSUE TITLE
Ampache 3.8.5

### ISSUE THREAD

**Issue by aruhier** [victor-rds/docker-ampache-fpm#2]
Hi,
Could you trigger a new build for Ampache 3.8.5 please?

Thanks!

**Comment by victor-rds** [comment]
Done, when I have some spare time I will write a hook to trigger every month at least

**Comment by aruhier** [comment]
Thanks! You can just setup a cronjob in dockerhub to trigger a new build every day/week/month if you want (and it's quite easy to do).
